---
name: 02 Build with BuildKit Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

#NEW: (START) ##########################################################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#NEW: (END) ############################################################
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: alvisisme/docker-ci-automation:test